<?php 
/***********
 * for the display of the Displaying PDF Flyers
 * 
 * 
 */
$baseurl =Mage::getBaseUrl();
$cust_id = Mage::registry('customer_id');
$cust_email = Mage::registry('customer_email');
$read = Mage::getSingleton('core/resource')->getConnection('core_read');
$sql  = "Select * from `pdf_flyer` WHERE `user_id`='$cust_id'";
$read->query($sql);
$getrows = $read->fetchAll($sql);
?>
<div class="netcode-dashboard">
	<div class="page-title">
        <h1><?php echo $this->__('PDF Flyers');?></h1>
    </div>
<div class="pdfflyersection">
	<div class="sec1">
		<a href="<?php echo $baseurl;?>customer/disttools/createpdfs/"><?php echo $this->__('Create New Flyer');?></a>
	</div>
	<div class="sec2">
		<table border="0" style="width: 100%;margin-top: 40px;">
			<tr>
				<td style="border-right: 1px solid #D6D6D6;border-left: 1px solid #D6D6D6;border-top: 1px solid #D6D6D6;padding: 10px 0px 10px 10px;background: #D6D6D6;border-bottom: none;"><strong><?php echo $this->__('ID');?></strong></td>
				<td style="border-right: 1px solid #D6D6D6;border-left: 1px solid #D6D6D6;border-top: 1px solid #D6D6D6;padding: 10px 0px 10px 10px;background: #D6D6D6;border-bottom: none;"><strong><?php echo $this->__('PDF Flyer');?></strong></td>
				<td style="border-right: 1px solid #D6D6D6;border-left: 1px solid #D6D6D6;border-top: 1px solid #D6D6D6;padding: 10px 0px 10px 10px;background: #D6D6D6;border-bottom: none;"><strong><?php echo $this->__('Sent To');?></strong></td>				
				<td style="border-right: 1px solid #D6D6D6;border-left: 1px solid #D6D6D6;border-top: 1px solid #D6D6D6;padding: 10px 0px 10px 10px;background: #D6D6D6;border-bottom: none;"><strong><?php echo $this->__('Created On');?></strong></td>				
				<td style="border-right: 1px solid #D6D6D6;border-left: 1px solid #D6D6D6;border-top: 1px solid #D6D6D6;padding: 10px 0px 10px 10px;background: #D6D6D6;border-bottom: none;"></td>
			</tr>
		<?php
		$i=0;
			foreach($getrows as $rownew){
			?>
			<tr>
				<td style="border: 1px solid #B5B5B5;padding: 10px 0px 10px 10px;">
					<?php echo $rownew['id'];?>
				</td>
				<td style="border: 1px solid #B5B5B5;padding: 10px 0px 10px 10px;">
					<?php echo $rownew['flyername'];?>
				</td>
				<td style="border: 1px solid #B5B5B5;padding: 10px 0px 10px 10px;">
					<?php echo $rownew['email'];?>
				</td>
				<td style="border: 1px solid #B5B5B5;padding: 10px 0px 10px 10px;">
					<?php echo $rownew['date'];?>
				</td>
				<td style="border: 1px solid #B5B5B5;padding: 10px 0px 10px 10px;">
					<form id="pdfsubmitform" method="POST" action="<?php echo $baseurl;?>customer/disttools/flysavesendemails/">
					<input type="hidden" name="rowid" id="rowid" value="<?php echo $rownew['id'];?>"/>
					<input type="hidden" name="userid" id="userid" value="<?php echo $rownew['user_id'];?>"/>
					<button id="flysubmit" name="flysubmit"><?php echo $this->__('Mail');?></button>
					</form>
					<form id="pdfdeleteform<?php echo $i;?>" method="POST">
					<input type="hidden" name="rowid" id="rowid" value="<?php echo $rownew['id'];?>"/>
					<input type="hidden" name="userid" id="userid" value="<?php echo $rownew['user_id'];?>"/>
					<button id="flydelete<?php echo $i;?>" class="flydelete" name="flydelete"><?php echo $this->__('X');?></button>
					</form>
				</td>				
			</tr>
			<script type="text/javascript">
			jQuery('#flydelete<?php echo $i;?>').on( "click", function(){
			//alert('hi');
			var baseurl = '<?php echo $baseurl;?>';
			var formData = new FormData(jQuery('#pdfdeleteform<?php echo $i;?>')[0]);
			//alert(formData);
			jQuery.ajax({
							url: baseurl+'customer/disttools/pdfdelete/',
							type: 'POST',
							data: formData,
							async: false,            
							success: function (data) {
								alert(data);
								location.reload();			
							},
							cache: false,
							contentType: false,
							processData: false
			});

			return false;
			});
			</script>
			<?php
			$i++;
			} 
		?>
		</table>
	</div>
</div>
</div>


