<?php 
$flyer_content = Mage::registry('flyer_content');
$flyer_images = Mage::registry('flyer_images');
$flytemplate = $flyer_content['flytemplate'];
$flyername = $flyer_content['flyername'];
$headertext = $flyer_content['headertext'];
$footertext = $flyer_content['footertext'];
$prod_ids = $flyer_content['flysearchvalues'];
$logo = $flyer_images['logo'];
$logocustom = $flyer_images['logocustom'];
$prodArray = explode(',', $prod_ids);
$logoval = Mage::getDesign()->getSkinUrl().'images'.DS.'pdfflyer'.DS.$img1['file'];
echo '<div class="pdf_reviewset">
	<div class="pdf_head">
		<div class="pdf_h_l">';
echo '<img src="'.$logo.'" width="150">';
echo '</div><div class="pdf_h_r">';
if($headertext){
	echo $headertext;
}else{
	echo '<img src="'.$logocustom.'" width="150">';
}
echo '</div>
	</div>
	<div class="pdf_body">';
if($flytemplate =='teaser'){
echo '
<div class="products-grid">
	<div class="row">
	<div class="yt-products-container clearfix">';
foreach($prodArray as $prod_id){
	$obj = Mage::getModel('catalog/product');
	$_product = $obj->load($prod_id);
	$_helper = $this->helper('catalog/output');

echo '<div class="item col-lg-3 col-md-3 col-sm-6 col-xs-12"> 
		<div class="item-inner">
			<div class="product-image">
							<a href="'.$_product->getProductUrl().'" title="'.$this->stripTags($this->getImageLabel($_product, 'small_image'), null, true).'" class="product-image">
								<img id="product-collection-image-'.$_product->getId().'"
								src="'.$this->helper('catalog/image')->init($_product, 'small_image')->resize(150,150).'"
								alt="'.$this->stripTags($this->getImageLabel($_product, 'small_image'), null, true).'" />
							</a>
			</div>
			<div class="product-info">
							<div class="product-name">
								<a href="'.$_product->getProductUrl() .'" title="'.$this->stripTags($_product->getName(), null, true).'">';
								if( strlen($_helper->productAttribute($_product, $_product->getName(), 'name')) > 100 ){
									 echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0, 100);
                                } else {
                                    echo $_helper->productAttribute($_product, $_product->getName(), 'name');
                                }
								echo '</a>
							</div>
							<div class="prod_sku"><span>'.$this->__('Style:').'</span>'. $_product->getSKU().'</div>
							<div class="wishlist-compare prod_id">
								'.$_product->getPriceHtml($_product, true).'
                            </div>
			</div>
		</div>
	</div>';
}
echo '</div></div></div>';	
}else{
echo '<div class="products-list">
	<div class="row">
	<div class="yt-products-container clearfix"><ol class="products-list" >';
foreach($prodArray as $prod_id){
	$obj = Mage::getModel('catalog/product');
	$_product = $obj->load($prod_id);
	$_helper = $this->helper('catalog/output');

echo '
		<li class="item">
			<div class="item-inner">
				<div class="product-list-left col-lg-3 col-md-3 col-sm-5 col-xs-12">
                        <div class="product-image">
							<a href="'.$_product->getProductUrl().'" class="product-img" title="'.$this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) .'">
								<img id="product-collection-image-'.$_product->getId().'"
								src="'.$this->helper('catalog/image')->init($_product, 'small_image')->resize(150,150).'"
								alt="'.$this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) .'" />
							</a>
						</div>
				</div>
				<div class="product-info col-lg-8 col-md-8 col-sm-7 col-xs-12">
						<div class="product-name">
							<a href="'.$_product->getProductUrl().'" title="'.$this->stripTags($_product->getName(), null, true).'">';
							if( strlen($_helper->productAttribute($_product, $_product->getName(), 'name')) > 100 ){
									 echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0, 100);
                                } else {
                                    echo $_helper->productAttribute($_product, $_product->getName(), 'name');
                                }
							echo '</a>
						</div>   
						<div class="prod_sku">
							<span>'.$this->__('Style:').'</span>'. $_product->getSKU().'
						</div>
						<div class="product-addto-wrap">
							<a class="link-compare" href="'.$this->getAddToCompareUrl($_product).'" title="'.$this->__('Add to Compare').'" style="color: black;">
								Add to Compare
							</a>
							<a href="'.$_product->getProductUrl().'" class="link-view" title="'.$this->stripTags($_product->getName(), null, true).'" style="color: black;">
                             View Details
                            </a>
						</div>
				</div>
			</div>
		</li>
';
}	
echo '</ol></div></div></div>';
}
echo '</div>
<div class="pdf_footer">
'.$footertext.'
</div>
</div>';
