<?php 
if(Mage::getSingleton('customer/session')->isLoggedIn()) {
     $customerData = Mage::getSingleton('customer/session')->getCustomer();
      $customer_id = $customerData->getId();
 }
$baseurl = Mage::getBaseUrl();
$_productCollection = Mage::getModel('catalog/product')
							->getCollection()
							->addAttributeToSort('created_at', 'DESC')
							->addAttributeToSelect('*')
							->load();
$conn = Mage::getSingleton('core/resource')->getConnection('core_read');
$query = 'SELECT selectproducts FROM prodselect WHERE vendorid = '. (int)$customer_id;
$selectquery = $conn->fetchRow($query);

$newselect = unserialize($selectquery['selectproducts']);
$newremarray = '954, 955';
//print_r($newselect);
?>
<div class="vendor-prodselect">
	<div class="page-title">
        <h1><?php echo $this->__('Vendor Product Selection');?></h1>
    </div>
	<div class="vendor-panel">
		<div id="success1"></div>
		<form method="POST" id="productsave" name="productsave">
			<div class="ven">
					<h2><?php echo $this->__('Select the products to be listed');?></h2>
			</div>
			
			<div class="vendor">
				<div class="ven-a">
					<label for="prodselect">
						<h2><?php echo $this->__('Products list:');?></h2>
					</label>
				</div>
				<div class="ven-b">
					<select name="prod_select[]" id="prod_select" multiple>	
						<?php 
						foreach ($_productCollection as $_product){
							$customer_group = $_product->getAttributeText('custom_groups');
							if($customer_group !="distributor"){
								if((in_array($_product->getId(), $newselect))){
									
									echo '<option value="'.$_product->getId().'" selected>'.$_product->getName().'</option>';
								}else{
									echo '<option value="'.$_product->getId().'">'.$_product->getName().'</option>';
								}
							}
						}
						?>
					</select>
					<div class="hint"><?php echo $this->__('<b>Hint:</b> You can select multiple products by pressing ctrl key.');?></div>
				</div>				
			</div>
			<div class="ven">
					<input type="hidden" name="cust_id" id="cust_id" value="<?php echo $customer_id;?>">
					<button type="submit" id="prodselectbyvendor" name="prodselectbyvendor"><?php echo $this->__('Submit');?></button>
			</div>	
		</form>
	</div>
</div>
<script>
	jQuery('#prodselectbyvendor').click(function(){				
		var baseurl = '<?php echo $baseurl;?>';
		var formData = new FormData(jQuery('#productsave')[0]);
		if( !jQuery('#prod_select').val() ){
			alert('please select some products!');
			return false;
		}else{
			jQuery.ajax({
							url: baseurl+'prodselect/index/prodsaves/',
							type: 'POST',
							data: formData,
							async: false, 
							success: function (data) {
								if(data='committed'){
									html = '<div class="msgsuccess">Success. Vendor details have been successfully saved</div>';
									jQuery('#success1').append(html);
									setTimeout(function() {
									jQuery('.msgsuccess').remove();
									}, 3500);
								}
							},
							cache: false,
							contentType: false,
							processData: false
							
		});
		}
		return false;
	});
</script>
