<?php 
$vendorname = Mage::registry('vendorname');
$_helper =  Mage::helper('catalog/output');
$proddetails = Mage::registry('vendorsingleproduct');
$_product = Mage::getModel('catalog/product')->load($proddetails); 
?>
<title><?php echo $_helper->productAttribute($_product, $this->htmlEscape($_product->getName()), 'name') ?></title>
<meta name="format-detection" content="Vendor Shop">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="description" content="<?php echo $description;?>">
<meta name="keywords" content="Magento, Varien, E-commerce, <?php echo $vendortitle;?>">
<meta name="robots" content="INDEX,FOLLOW">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>js/calendar/calendar-win2k-1.css">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/bootstrap/css/bootstrap.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/bootstrap/css/bootstrap-theme.min.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/css/font-awesome.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/css/fontsocialico.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/css/addons.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/css/theme.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/css/menu.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/css/css3.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/basicproducts/css/style.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/cartpro/css/cartpro.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/categories/css/sm-categories.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/deal/css/sm_deal.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/megamenu/css/horizontal/black/megamenu.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/megamenu/css/vertical/black/megamenu.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/quickview/css/quickview.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/searchboxpro/css/searchboxpro.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/shopby/css/style.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/tablisting/css/tablisting.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/listingextend/css/style.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/listingdeals/css/animate.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/listingdeals/css/sm-listing-deals.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/css/jquery.fancybox.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/css/cloudzoom.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/css/imageslider.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/css/new_cpanel.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/css/yt-responsive.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/css/colors/yellow.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/css/configurableswatches.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/base/default/css/formbuilder/custom.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/cameraslide/css/cameraslide.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/base/default/openstream/custom_listing.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/css/print.css" media="print">
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/prototype/prototype.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/lib/ccard.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/prototype/validation.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/scriptaculous/builder.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/scriptaculous/effects.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/scriptaculous/dragdrop.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/scriptaculous/controls.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/scriptaculous/slider.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/varien/js.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/varien/form.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/varien/menu.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/mage/translate.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/mage/cookies.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/calendar/calendar.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/calendar/calendar-setup.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/varien/product.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/varien/configurable.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/varien/weee.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/jquery.noconflict.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/jsmart.noconflict.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/jquery.uniform.min.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/jquery.jqtransform.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/yt-script.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/yt-extend.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/cloud-zoom.1.0.2.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/jcarousellite_1.0.1.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/jquery.easing.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/jquery.cookie.min.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/jquery.accordion_snyderplace.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/respond.src.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/jquery.fancybox.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/fancybox-buttons.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/bundle.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/base/default/js/owl.carousel.min.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/jquery.session.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/ytcpanel.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/lib/modernizr.custom.min.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/lib/selectivizr.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/lib/matchMedia.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/lib/matchMedia.addListener.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/lib/enquire.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/configurableswatches/product-media.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/configurableswatches/swatches-list.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/configurableswatches/swatches-product.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/app.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/js/lib/imagesloaded.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/cameraslide/js/camera.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/cameraslide/js/enfinity.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/cameraslide/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/sm_market/default/sm/cameraslide/js/jquery.mobile.customized.min.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>skin/frontend/base/default/js/msrp.js"></script>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('#custommobileset').click(function(){
		jQuery('#custom_menusambar').slideToggle('slow','linear');
	});
});
</script>
<script type="text/javascript">
//<![CDATA[
optionalZipCountries = ["HK","IE","MO","PA"];
//]]>
</script>
<script type="text/javascript">//<![CDATA[
        var Translator = new Translate([]);
        //]]></script>
<script type="text/javascript">
//<![CDATA[
	var SKIN_URL = '<?php echo $baseurl;?>skin/frontend/default/sm_market';
	var TMPL_NAME = 'sm_market';
	var TMPL_COOKIE = ["theme_color","layoutstyle","menustyle"];
//]]>
</script>
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans" media="all">
