<?php
$proddetails = Mage::registry('vendorsingleproduct');
$var_value = Mage::registry('vendordetails');
$vendorname = Mage::registry('vendorname');
$vendortitle = str_replace('-', ' ', $vendorname);
$baseurl = Mage::getBaseUrl();
$vendor_id = $var_value['vendor_id'];
$vendorname = $var_value['vendorname'];
$vendortitle = str_replace('-', ' ', $vendorname);
$vendorlogo = $var_value['vendorlogo'];
$vendorphone = $var_value['vendorphone'];
$address = $var_value['address'];
$vendor_url = $var_value['vendor_url'];
$customer = Mage::getModel('customer/customer')->load($vendor_id)->getData();
$customer_email = $customer['email'];
?>
<body id="bd" class="sm_market vendorshop <?php echo $vendorname;?> shop-index">
<div id="yt_wrapper">
	<div id="yt_header" class="yt-header wrap header1-wrap">		     
		<div class="yt-header-middle">
			<div class="container">
				<div class="row">
					<div class="logo col-lg-2 col-md-2 col-sm-12 col-xs-12">
						<div class="logo1">
							<a href="<?php echo $vendor_url;?>" title="<?php echo $vendortitle;?>" class="logo"><img src="<?php echo $vendorlogo;?>" alt="thecapcompany"></a>
						</div>
					</div>
					<div class="header-middle-right col-lg-10 col-md-10 col-sm-12 col-xs-12">
						<div class="topmenuset">
							<div class="sm_megamenu_wrapper_horizontal_menu sambar">
								<div class="sambar-inner">
										<a class="btn-sambar" data-sapi="collapse" id="custommobileset">
											<span class="icon-bar"></span>
											<span class="icon-bar"></span>
											<span class="icon-bar"></span>
										</a>
										<ul class="sm-megamenu-hover sm_megamenu_menu sm_megamenu_menu_black"  id="custom_menusambar" data-jsapi="on">
											<li class=" other-toggle sm_megamenu_lv1 sm_megamenu_drop parent   ">
												<a class="sm_megamenu_head sm_megamenu_drop " href="<?php echo $baseurl.'shop'.DS.$vendorname.DS;?>" id="sm_megamenu_165">
													<span class="sm_megamenu_title">Home</span>
												</a>
											</li>
											<li class=" other-toggle sm_megamenu_lv1 sm_megamenu_drop parent   ">
												<a class="sm_megamenu_head sm_megamenu_drop " href="<?php echo $baseurl.'shop'.DS.$vendorname.DS.'about'.DS?>" id="sm_megamenu_162">
													<span class="sm_megamenu_title">About Us</span>
												</a>
											</li>
											<li class=" other-toggle sm_megamenu_lv1 sm_megamenu_drop parent   ">
												<a class="sm_megamenu_head sm_megamenu_drop " href="<?php echo $baseurl.'shop'.DS.$vendorname.DS.'howtoorder'.DS?>" id="sm_megamenu_167">
													<span class="sm_megamenu_title">How To Order</span>								                                
												</a>
											</li>
											<li class=" other-toggle sm_megamenu_lv1 sm_megamenu_drop parent   ">
												<a class="sm_megamenu_head sm_megamenu_drop " href="<?php echo $baseurl.'shop'.DS.$vendorname.DS.'contact'.DS?>" id="sm_megamenu_169">
													<span class="sm_megamenu_title">Contact</span>
												</a>
											</li>
										</ul>
								</div><!--sambar-inner-->
							</div><!--sm mega menu wrapper-->
						</div><!--topmenuset-->
						<div class="head-searchbox">
							<div class="top-right-search">
								<div class="topphone" style="float: right;">
									<div><span><?php echo '<strong>Contact:&nbsp</strong>'.$vendorphone;?></span><span><?php echo '&nbsp<strong>Email:&nbsp</strong>'.$customer_email;?></span></div>
								</div>
								<form id="search_mini_form" action="<?php echo $baseurl;?>catalogsearch/result/" method="get">
								<div class="form-search simple-search">
								<span class="search-icon">
								</span>
								<input id="search" type="text" name="q" value="" class="input-text" autocomplete="off">
								<div id="search_autocomplete" class="search-autocomplete" style="display: none;"></div>
								<button type="submit" title="Search" class="button">Search
								<script type="text/javascript">
								//<![CDATA[
								var searchForm = new Varien.searchForm('search_mini_form', 'search', 'Search...');
								searchForm.initAutocomplete('<?php echo $baseurl;?>catalogsearch/ajax/suggest/', 'search_autocomplete');
								//]]>
								</script>
								</button></div>
								</form>
							</div>
						</div>
					</div><!-- header middle right-->
				</div><!--row-->
			</div><!--container-->
		</div><!-- header middle-->
		<div class="yt-header-bottom">
			<div class="container">
				<div class="row">
					<div id="yt_header_left" class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
						<div id="yt_menu_short">
							<div id="btn_categories">
								<span><i class="icon-cate"></i>Cap Categories</span>
							</div>
							<div class="yt-menu-content">
									<?php $block1 = $this->getLayout()->createBlock('core/template');
										$block1->setTemplate('stallioni/shop/topmenu.phtml');
										echo $block1->toHtml(); 
									 ?>
							</div>
						</div><!--yt menu short-->
					</div><!--yt header left-->
				</div><!--row-->
			</div><!--container-->
		</div><!--yt header bottom-->
	</div><!--yt_header-->
