<?php
$var_value = Mage::registry('vendordetails');
$vendor_id = $var_value['vendor_id'];
$vendorname = $var_value['vendorname'];
$vendortitle = str_replace('-', ' ', $vendorname);
$vendorlogo = $var_value['vendorlogo'];
$vendorphone = $var_value['vendorphone'];
$address = $var_value['address'];
$vendor_url = $var_value['vendor_url'];
$customer = Mage::getModel('customer/customer')->load($vendor_id)->getData();
$customer_address_id = $customer['default_billing'];
$defaultBillingAddress = Mage::getModel('customer/address')->load($customer_address_id);
$customer_email = $customer['email'];
$company = $defaultBillingAddress['company'];
$conn = Mage::getSingleton('core/resource')->getConnection('core_read');
$query = 'SELECT selectproducts FROM prodselect WHERE vendorid = '. (int)$vendor_id;
$selectquery = $conn->fetchRow($query);
$newselect = unserialize($selectquery['selectproducts']);
$baseurl = Mage::getBaseUrl();
?>
<title><?php echo ucfirst($vendorname)?></title>
<?php
Mage::register('vendorname', $vendorname);
$block = $this->getLayout()->createBlock('core/template');
		$block->setTemplate('stallioni/shop/header.phtml');
		echo $block->toHtml(); 
?>
<body id="bd" class="sm_market vendorshop <?php echo $vendorname;?> shop-index">
<div id="yt_wrapper">
	<div id="yt_header" class="yt-header wrap header1-wrap">		     
		<div class="yt-header-middle">
			<div class="container">
				<div class="row">
					<div class="logo col-lg-2 col-md-2 col-sm-12 col-xs-12">
						<div class="logo1">
							<a href="<?php echo $vendor_url;?>" title="<?php echo $vendortitle;?>" class="logo"><img src="<?php echo $vendorlogo;?>" alt="thecapcompany"></a>
						</div>
					</div>
					<div class="header-middle-right col-lg-10 col-md-10 col-sm-12 col-xs-12">
						<div class="topmenuset">
							<div class="sm_megamenu_wrapper_horizontal_menu sambar">
								<div class="sambar-inner">
										<a class="btn-sambar" data-sapi="collapse" id="custommobileset">
											<span class="icon-bar"></span>
											<span class="icon-bar"></span>
											<span class="icon-bar"></span>
										</a>
										<ul class="sm-megamenu-hover sm_megamenu_menu sm_megamenu_menu_black"  id="custom_menusambar" data-jsapi="on">
											<li class=" other-toggle sm_megamenu_lv1 sm_megamenu_drop parent   ">
												<a class="sm_megamenu_head sm_megamenu_drop " href="<?php echo $baseurl.'shop'.DS.$vendorname.DS;?>" id="sm_megamenu_165">
													<span class="sm_megamenu_title">Home</span>
												</a>
											</li>
											<li class=" other-toggle sm_megamenu_lv1 sm_megamenu_drop parent   ">
												<a class="sm_megamenu_head sm_megamenu_drop " href="<?php echo $baseurl.'shop'.DS.$vendorname.DS.'about'.DS?>" id="sm_megamenu_162">
													<span class="sm_megamenu_title">About Us</span>
												</a>
											</li>
											<li class=" other-toggle sm_megamenu_lv1 sm_megamenu_drop parent   ">
												<a class="sm_megamenu_head sm_megamenu_drop " href="<?php echo $baseurl.'shop'.DS.$vendorname.DS.'howtoorder'.DS?>" id="sm_megamenu_167">
													<span class="sm_megamenu_title">How To Order</span>								                                
												</a>
											</li>
											<li class=" other-toggle sm_megamenu_lv1 sm_megamenu_drop parent   ">
												<a class="sm_megamenu_head sm_megamenu_drop " href="<?php echo $baseurl.'shop'.DS.$vendorname.DS.'contact'.DS?>" id="sm_megamenu_169">
													<span class="sm_megamenu_title">Contact</span>
												</a>
											</li>
										</ul>
								</div><!--sambar-inner-->
							</div><!--sm mega menu wrapper-->
						</div><!--topmenuset-->
						<div class="head-searchbox">
							<div class="top-right-search">
								<div class="topphone" style="float: right;">
									<div><?php echo '<strong>Contact:&nbsp</strong>'.$vendorphone;?></div>
									<div><?php echo '<strong>Email:&nbsp</strong>'.$customer_email;?></div>
								</div>								<form id="search_mini_form" action="<?php echo $baseurl;?>catalogsearch/result/" method="get">
								<div class="form-search simple-search">
								<span class="search-icon">
								</span>
								<input id="search" type="text" name="q" value="" class="input-text" autocomplete="off">
								<div id="search_autocomplete" class="search-autocomplete" style="display: none;"></div>
								<button type="submit" title="Search" class="button">Search
								<script type="text/javascript">
								//<![CDATA[
								var searchForm = new Varien.searchForm('search_mini_form', 'search', 'Search...');
								searchForm.initAutocomplete('<?php echo $baseurl;?>catalogsearch/ajax/suggest/', 'search_autocomplete');
								//]]>
								</script>
								</button></div>
								</form>
							</div>
						</div>
					</div><!-- header middle right-->
				</div><!--row-->
			</div><!--container-->
		</div><!-- header middle-->
	</div><!--yt_header-->
	<div id="yt_content" class="yt-content wrap">
		<div id="yt_main" class="yt-main col-main">
			<div class="yt-main-inner yt-content-inner">
				<div class="container">
					<div class="row">
						<div class="columns-w">
							<div id="yt_main" class="yt-main-left yt-main col-main col-lg-12 col-md-12 col-sm-4 col-xs-12">
								<div id="yt_header_left" class="col-lg-3 col-md-3 col-sm-0 col-xs-12">
									<div class="yt-menu">
									<div id="btn_categories">
									<span><i class="icon-cate"></i><?php echo $this->__("Cap Categories"); ?></span>
									</div>
									<div class="yt-menu-content">
									<?php $block1 = $this->getLayout()->createBlock('core/template');
										$block1->setTemplate('stallioni/shop/topmenu.phtml');
										echo $block1->toHtml(); 
									 ?>
									</div>
									</div>
								</div>
								<div id="yt_header_right" class="col-main col-lg-9 col-md-9 col-sm-12 col-xs-12"> 
								<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('vendor-slider-home')->toHtml();?>
								<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner-under-slider')->toHtml();?>
								</div>
								<div class="clear"></div>
								<div class="banner-home" style="margin-top:10px;">
								<div class="banner2 banner2-1 col-lg-4 col-md-4 col-sm-6 col-xs-12"><a href="<?php echo $vendor_url;?>"><span><?php echo $this->__('Cap Styles');?></span><img alt="" src="<?php echo $baseurl;?>media/wysiwyg/caps/cap1.png"></a></div>
								<div class="banner2 banner2-2 col-lg-4 col-md-4 col-sm-6 col-xs-12"><a href="<?php echo $vendor_url;?>"><span><?php echo $this->__('Customize');?></span><img src="<?php echo $baseurl;?>media/wysiwyg/caps/cap2.jpg" alt=""></a></div>
								<div class="banner2 banner2-3 col-lg-4 col-md-4 col-sm-6 col-xs-12"><a href="<?php echo $vendor_url;?>capoptions/"><span><?php echo $this->__('Cap Options');?></span><img src="<?php echo $baseurl;?>media/wysiwyg/caps/cap3.jpg" alt=""></a></div>
								</div>
								<div class="clear"></div>
								<div id="home-listing" class="col-main col-lg-12 col-md-12 col-sm-12 col-xs-12">
									<?php
										Mage::register('vendorid', $vendor_id);
										Mage::register('vendorurl',$vendor_url);
										$block1 = $this->getLayout()->createBlock('core/template');
										$block1->setTemplate('stallioni/shop/homeprodslider.phtml');
										echo $block1->toHtml(); 
									 ?>
								</div><!--home listing-->
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div><!--yt_content-->
<?php
$block->setTemplate('stallioni/shop/footer.phtml');
echo $block->toHtml(); 
?>
</div><!--yt_wrapper-->
</body>
