<script type="text/javascript" src="<?php echo Mage::getBaseUrl();?>js/tiny_mce/tiny_mce_jquery.js"></script>
<?php 
 if(Mage::getSingleton('customer/session')->isLoggedIn()) {
     $customerData = Mage::getSingleton('customer/session')->getCustomer();
      $customer_id = $customerData->getId();
 }
 $baseurl = Mage::getBaseUrl();
 $resource = Mage::getSingleton('core/resource')->getConnection('core_read');
 $query = 'SELECT * FROM vendorpage_about WHERE vendorid = '. (int)$customer_id;
 $selectquery = $resource->fetchAll($query);
 $selectquery1 = $resource->fetchRow($query);
 $data = $selectquery1['about'];
 $count = count($selectquery);
?>

<script type="text/javascript">
window.onload=function()
{
   tinyMCE.init({
    mode : "exact",
    elements: "vendordesc",
    theme : "advanced",
    width : "800px",
    height : "480",
    menubar: false,
    plugins : "inlinepopups,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
    theme_advanced_buttons1 : "bold,italic,underline,|,justifyleft,justifycenter,justifyright,justifyfull,code,|,styleselect,formatselect,fontselect,fontsizeselect,image",
    theme_advanced_buttons2 : "",
    theme_advanced_buttons3 : "",
    //theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
    //theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
    //theme_advanced_buttons2 : "help,code",
    //theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
    //theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,|,visualchars,nonbreaking",
    //theme_advanced_toolbar_location : "top",
    //theme_advanced_toolbar_align : "left",
    //theme_advanced_path_location : "bottom",
    extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
   // theme_advanced_resize_horizontal : 'true',
   // theme_advanced_resizing : 'true',
    apply_source_formatting : 'true',
    convert_urls : 'false',
    force_br_newlines : 'true',
    doctype : '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'

  });
};
</script>

<div class="vendor-dashboard">
	<div class="page-title">
		<h1><?php echo $this->__('Distributor About Us');?></h1>
	</div>
	<div class="vendor-panel">
		<div id="success"></div>
		<form method="POST" name="vendorabout" id="vendorabout">
			<div class="vendor">
				<div class="ven"><?php echo $this->__('Please enter the description describing about the company.');?></div>
				<div class="ven">
					<?php if($count=='1'){?>
					<textarea name="vendordesc" id="vendordesc"><?php echo $data;?></textarea>	
					<?php }else{?>
					<textarea name="vendordesc" id="vendordesc"></textarea>
					<?php }?>			
				</div>					
			</div>
			<div class="vendor">
				<div class="ven">
					<input type="hidden" name="cust_id" id="cust_id" value="<?php echo $customer_id;?>"/>
					<button type="submit" id="vendoraboutsubmit" name="vendoraboutsubmit"><?php echo $this->__('Submit');?></button>
				</div>
			</div>
		</form>
	</div>
</div>
<script>
	jQuery('#vendoraboutsubmit').click(function(){		
		var tinycontent = tinymce.get('vendordesc').getContent();
		var cust_id = jQuery('#cust_id').val();
		var baseurl = '<?php echo $baseurl;?>';
		if(tinycontent ==""){
			alert('please Enter the descrption!');
			return false;
		}else{
			jQuery.ajax({
							url: baseurl+'about/index/aboutsave/',
							type: 'POST',
							data: { cust_id: cust_id, tinycontent: tinycontent },
							success: function (data) {
								if(data='committed'){
									html = '<div class="msgsuccess">Success. Vendor details have been successfully saved</div>';
									jQuery('#success').append(html);
									setTimeout(function() {
									jQuery('.msgsuccess').remove();
									}, 3500);
									jQuery('#vendordesc').val("");
								}
							},
		});
		}

		return false;
	});
</script>
